<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_PopularBest Sellers</name>
   <tag></tag>
   <elementGuidId>ffe3493f-0412-48fe-9b4f-331f67a65bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home-page-tabs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='home-page-tabs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PopularBest Sellers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>1e25d04f-e702-4775-9202-9c6d083e9db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-page-tabs</value>
      <webElementGuid>947afc30-8f0f-41c7-b806-3cd09ee327d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav nav-tabs clearfix</value>
      <webElementGuid>e61c1434-3066-45e3-ba38-f6bf8df74d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			PopularBest Sellers
		</value>
      <webElementGuid>7eb92ae3-c80b-41dc-bcdb-9801f920ddf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-page-tabs&quot;)</value>
      <webElementGuid>a6e70ed0-5331-4f19-bc95-eec26b2caf56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='home-page-tabs']</value>
      <webElementGuid>90cf2443-426c-482f-a93c-6a3864f8da96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center_column']/ul</value>
      <webElementGuid>e9f4b2e7-4c18-4375-b820-8258c4caebd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::ul[2]</value>
      <webElementGuid>7206397d-1f76-4dfd-972a-16ffe16e025b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::ul[2]</value>
      <webElementGuid>e0cc492d-2766-45af-ba4f-854e5fabd26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul</value>
      <webElementGuid>54214ac5-0c8a-408a-9f9e-becd08fcc625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'home-page-tabs' and (text() = '
			PopularBest Sellers
		' or . = '
			PopularBest Sellers
		')]</value>
      <webElementGuid>89290e2c-c80b-4cca-864a-af3100e6e1f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
