<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Number of Products</name>
   <tag></tag>
   <elementGuidId>f104b700-71a0-4954-8953-9269c7222a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#summary_products_quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='summary_products_quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1 product&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e3003d7-2647-4ccc-8b05-b017e3de0ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>summary_products_quantity</value>
      <webElementGuid>854d7eab-3577-4f5b-98be-57b2421d7ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 product</value>
      <webElementGuid>11e16115-1dca-4cdc-bf76-178ec991c1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;summary_products_quantity&quot;)</value>
      <webElementGuid>b8a54622-714f-4f96-9b19-2f6ca5dcc8c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='summary_products_quantity']</value>
      <webElementGuid>0a1dab10-c0f4-4620-9930-795dcd1968d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='cart_title']/span/span</value>
      <webElementGuid>2e0a6a47-6950-4d75-9773-bb798b17332f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 product']/parent::*</value>
      <webElementGuid>59491126-6823-4079-bd70-9baa802ee8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span/span</value>
      <webElementGuid>c0be498f-0dd4-4cb7-9b7d-e734fdadd0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'summary_products_quantity' and (text() = '1 product' or . = '1 product')]</value>
      <webElementGuid>5b7ff959-dfda-461a-8094-1c7a68954559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
