<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Color_White</name>
   <tag></tag>
   <elementGuidId>b242f39a-a5f4-47a7-9c2f-c7364c675f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#color_8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='color_8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;White&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6eb84fa0-0683-4ce4-9169-49b263368054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.automationpractice.pl/index.php?id_product=2&amp;controller=product</value>
      <webElementGuid>efd4c19c-5bfb-456b-9962-bdc858a22c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color_8</value>
      <webElementGuid>8b02beae-6b3b-4a78-8720-589d2c1b4dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>White</value>
      <webElementGuid>e79ccca7-cdda-4756-a0e4-8adb9e6c5356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color_pick</value>
      <webElementGuid>3b321c54-14e5-49c0-867d-cc49531d7eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>White</value>
      <webElementGuid>e1c51a9f-e191-40fa-9e4b-ee89c98565ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color_8&quot;)</value>
      <webElementGuid>9680a398-f65b-4e1c-940d-268667467c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='color_8']</value>
      <webElementGuid>d1214402-fd9a-4b5e-b6fe-6d387d4e8f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='color_to_pick_list']/li/a</value>
      <webElementGuid>750bb71d-cafd-45d9-88e9-7c25098c0384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::a[1]</value>
      <webElementGuid>47755eeb-273c-4759-8e53-11d6ebe32592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::a[2]</value>
      <webElementGuid>42f18a97-5ce1-4de1-aece-31fa40374d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data sheet'])[1]/preceding::a[2]</value>
      <webElementGuid>ebd92ffe-3cfb-4528-a673-1d7267da053f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://www.automationpractice.pl/index.php?id_product=2&amp;controller=product'])[2]</value>
      <webElementGuid>e564b71b-c4fb-4ba0-a397-b31a0ba2bee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/ul/li/a</value>
      <webElementGuid>6b024acf-3162-4cea-86e1-ae5a3e04087b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.automationpractice.pl/index.php?id_product=2&amp;controller=product' and @id = 'color_8' and @name = 'White' and @title = 'White']</value>
      <webElementGuid>444bf862-2b42-4dd4-9826-f08bbceb12bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
