<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blouse</name>
   <tag></tag>
   <elementGuidId>5a36f23b-66a1-46a0-ba93-5e9f422574af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.product-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='blockbestsellers']/li/div/div[2]/h5/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Blouse&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9030efd-8e07-4925-b6b3-3a0a11ab22b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>da799161-1a19-4b07-a4dc-52741906eb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.automationpractice.pl/index.php?id_product=2&amp;controller=product</value>
      <webElementGuid>c0f662e6-b3bd-4fd1-b941-db7c968c7c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Blouse</value>
      <webElementGuid>f11d2868-0753-4ec3-98f0-d82f8d060ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>939892ab-0d43-4d22-a737-7d23c016b601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Blouse
						</value>
      <webElementGuid>60a05dc2-9f8f-40d3-b5ae-0a25b011a279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blockbestsellers&quot;)/li[@class=&quot;ajax_block_product col-xs-12 col-sm-4 col-md-3 first-in-line first-item-of-tablet-line first-item-of-mobile-line hovered&quot;]/div[@class=&quot;product-container&quot;]/div[@class=&quot;right-block&quot;]/h5[1]/a[@class=&quot;product-name&quot;]</value>
      <webElementGuid>c35ad114-9ad7-4cc1-8e1a-ab887eaf4aba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='blockbestsellers']/li/div/div[2]/h5/a</value>
      <webElementGuid>aabf7774-45c5-434f-aac4-47dfe9a70c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Blouse')])[2]</value>
      <webElementGuid>ff899699-fc1a-4b4d-8158-ab4f2a51c221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$27'])[1]/following::a[1]</value>
      <webElementGuid>e7a4e08b-4e6e-4606-9792-ab6890777939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$27'])[2]/preceding::a[1]</value>
      <webElementGuid>78f92cf5-4964-43ed-b2b6-6e6cb4ab84e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::a[1]</value>
      <webElementGuid>0e5e4809-3e5f-4be8-8b0f-aad57d695e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blouse']/parent::*</value>
      <webElementGuid>3825aced-3e5b-4537-af03-6bca93c5facd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://www.automationpractice.pl/index.php?id_product=2&amp;controller=product'])[4]</value>
      <webElementGuid>48b2f759-a727-4cd0-acd8-30c9d8122921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/a</value>
      <webElementGuid>89378942-6534-46a4-bc96-57ebc25069fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.automationpractice.pl/index.php?id_product=2&amp;controller=product' and @title = 'Blouse' and (text() = '
							Blouse
						' or . = '
							Blouse
						')]</value>
      <webElementGuid>995fc13d-4abe-4b38-b470-3cd0973033b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
